### ISSUE TITLE
add list of contracts + addresses

### ISSUE THREAD

**Issue by jmonteer** [jmonteer/hegic-resources#3]

**Comment by 8ball030** [comment]
btcoptions: '0x3961245DB602eD7c03eECcda33eA3846bD8723BD'
btcpool: '0x20DD9e22d22dd0a6ef74a520cb08303B5faD5dE7'
btcpriceprovider: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
ethoptions: '0xEfC0eEAdC1132A12c9487d800112693bf49EcfA2'
ethpool: '0x878F15ffC8b894A1BA7647c7176E4C01f74e140b'
exchange: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'
hegic: '0x584bC13c7D411c00c01A62e8019472dE68768430'
priceprovider: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
stakingeth: '0x1Ef61E3E5676eC182EED6F052F8920fD49C7f69a'
stakingwbtc: '0x840a1AE46B7364855206Eb5b7286Ab7E207e515b'
wbtc: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599'

**Comment by tempted-eth** [comment]
rHEGIC - 0x47c0ad2ae6c0ed4bcf7bc5b380d7205e89436e84
LP ETH staking - 0x9b18975e64763bda591618cdf02d2f14a9875981
LP BTC staking - 0x202ec7190f75046348de5ab3a97cc45d7b440680

**Comment by jmonteer** [comment]
Can you guys commit to readme.md adding some format? 

You rock
